name: Biome
on:
  push:
    branches: [main]
  pull_request:
permissions:
  contents: read
  pull-requests: write
jobs:
  biome:
    name: Biome
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@c016c38f26f2c4a6eb3662679143614a254263fd # v2.3.0
      - name: Run Biome
        run: biome ci
