name: CI
on:
  merge_group: {}
  pull_request: {}
  push:
    branches: [main]
  workflow_dispatch: {}
permissions: {}
jobs:
  required:
    name: "Required Checks: CI"
    if: ${{ always() }}
    needs:
      - verify-author
      - changed-files
      - actionlint
      - ghalint
      - zizmor
      - biome
      - commitizen
      - editorconfig
      - mypy
      - ruff
      - yamllint
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Fail if any required jobs failed or cancelled
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        run: exit 1
  verify-author:
    name: Verify author
    environment: ${{ github.event_name == 'pull_request' &&
      endsWith(github.event.pull_request.user.login, '[bot]') &&
      contains(github.event.pull_request.labels.*.name, 'dependencies') &&
      contains(github.event.pull_request.labels.*.name, 'github_actions') && 'ci' || null }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Author has been verified
        run: exit 0
  changed-files:
    name: Get changed files
    if: ${{ github.event_name == 'pull_request' }}
    needs: verify-author
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    outputs:
      # reference: https://github.com/tj-actions/changed-files#outputs-
      actions: ${{ steps.changed-files.outputs.actions_any_modified == 'true' }}
      biome: ${{ steps.changed-files.outputs.biome_any_modified == 'true' }}
      python: ${{ steps.changed-files.outputs.python_any_modified == 'true' }}
      yamllint: ${{ steps.changed-files.outputs.yamllint_any_modified == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 50 # Assume PRs are less than 50 commits
          persist-credentials: true
      - name: Get relevant files changed per group
        id: changed-files
        uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # v47.0.0
        with:
          files_yaml: |
            common: &common
              - .github/workflows/ci.yml
            dependencies: &dependencies
              - .python-version
              - pyproject.toml
              - uv.lock
            actions:
              - "**/action.{yaml,yml}"
              - ".github/workflows/*.{yaml,yml}"
            biome:
              - *common
              - "**/*.{js,jsx,ts,tsx,cjs,cts,mjs,mts,json,jsonc,css,svelte,vue,astro,graphql,gql}"
            python:
              - *common
              - *dependencies
              - "**/*.py"
            yamllint:
              - *common
              - "**/*.{yaml,yml}"
  actionlint:
    name: actionlint
    if: ${{ always() && !failure() && !cancelled() &&
      (needs.changed-files.result == 'skipped' || needs.changed-files.outputs.actions == 'true') }}
    needs: changed-files
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Run actionlint
        uses: ponko2/actions/actionlint@10ab1b43e4cd5278bc41bd150d07cd51210275e7 # v1.2.0
  ghalint:
    name: ghalint
    if: ${{ always() && !failure() && !cancelled() &&
      (needs.changed-files.result == 'skipped' || needs.changed-files.outputs.actions == 'true') }}
    needs: changed-files
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Run ghalint
        uses: ponko2/actions/ghalint@10ab1b43e4cd5278bc41bd150d07cd51210275e7 # v1.2.0
  zizmor:
    name: zizmor
    if: ${{ always() && !failure() && !cancelled() &&
      (needs.changed-files.result == 'skipped' || needs.changed-files.outputs.actions == 'true') }}
    needs: changed-files
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Run zizmor
        uses: ponko2/actions/zizmor@10ab1b43e4cd5278bc41bd150d07cd51210275e7 # v1.2.0
  biome:
    name: Biome
    if: ${{ always() && !failure() && !cancelled() &&
      (needs.changed-files.result == 'skipped' || needs.changed-files.outputs.biome == 'true') }}
    needs: changed-files
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Set up Biome
        uses: biomejs/setup-biome@454fa0d884737805f48d7dc236c1761a0ac3cc13 # v2.6.0
      - name: Run Biome
        run: biome ci --error-on-warnings
  commitizen:
    name: Commitizen
    if: ${{ github.event_name == 'pull_request' }}
    needs: verify-author
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 50 # Assume PRs are less than 50 commits
          filter: blob:none
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@2ddd2b9cb38ad8efd50337e8ab201519a34c9f24 # v7.1.1
      - name: Set up Python
        run: uv python install
      - name: Validate all commits from PR
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        run: uvx --from commitizen cz check --rev-range "${BASE_SHA}..${HEAD_SHA}"
  editorconfig:
    name: EditorConfig
    needs: verify-author
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Set up EditorConfig checker
        uses: editorconfig-checker/action-editorconfig-checker@0ab3427a3f09b17c21d489172245be511e0a16ea # v2.0.0
      - name: Run EditorConfig checker
        run: editorconfig-checker
  mypy:
    name: mypy
    if: ${{ always() && !failure() && !cancelled() &&
      (needs.changed-files.result == 'skipped' || needs.changed-files.outputs.python == 'true') }}
    needs: changed-files
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@2ddd2b9cb38ad8efd50337e8ab201519a34c9f24 # v7.1.1
      - name: Set up Python
        run: uv python install
      - name: Install dependencies
        run: uv sync
      - name: Run mypy
        run: uv run -m mypy .
  ruff:
    name: Ruff
    if: ${{ always() && !failure() && !cancelled() &&
      (needs.changed-files.result == 'skipped' || needs.changed-files.outputs.python == 'true') }}
    needs: changed-files
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Set up Ruff
        uses: astral-sh/ruff-action@57714a7c8a2e59f32539362ba31877a1957dded1 # v3.5.1
      - name: Run Ruff check
        run: ruff check --fix
      - name: Run Ruff format
        run: ruff format --check
  yamllint:
    name: yamllint
    if: ${{ always() && !failure() && !cancelled() &&
      (needs.changed-files.result == 'skipped' || needs.changed-files.outputs.yamllint == 'true') }}
    needs: changed-files
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Run yamllint
        run: yamllint --format=github --strict .
