name: Commitizen
on:
  pull_request:
permissions:
  contents: read
jobs:
  commitizen:
    name: Commitizen
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@0c5e2b8115b80b4c7c5ddf6ffdd634974642d182 # v5.4.1
      - name: Set up Python
        run: uv python install
      - name: Validate all commits from PR
        run: >-
          uvx --from commitizen
          cz check --rev-range ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}
