name: Commitizen
on:
  pull_request:
permissions:
  contents: read
jobs:
  commitizen:
    name: Commitizen
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@c7f87aa956e4c323abf06d5dec078e358f6b4d04 # v6.0.0
      - name: Set up Python
        run: uv python install
      - name: Validate all commits from PR
        run: >-
          uvx --from commitizen
          cz check --rev-range ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}
