name: EditorConfig
on:
  push:
    branches: [main]
  pull_request:
permissions:
  contents: read
jobs:
  editorconfig:
    name: EditorConfig
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: editorconfig-checker/action-editorconfig-checker@0ab3427a3f09b17c21d489172245be511e0a16ea # v2.0.0
      - run: editorconfig-checker
