name: mypy
on:
  push:
    branches: [main]
  pull_request:
permissions:
  contents: read
jobs:
  mypy:
    name: mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@0c5e2b8115b80b4c7c5ddf6ffdd634974642d182 # v5.4.1
      - name: Set up Python
        run: uv python install
      - name: Install dependencies
        run: uv sync
      - name: Run mypy
        run: uv run -m mypy .
