name: mypy
on:
  push:
    branches: [main]
  pull_request:
permissions:
  contents: read
jobs:
  mypy:
    name: mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Set up Python
        run: uv python install
      - name: Install dependencies
        run: uv sync
      - name: Run mypy
        run: uv run -m mypy .
