name: reviewdog
on:
  push:
    branches: [main]
  pull_request:
permissions:
  contents: read
jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-yamllint@f01d8a48fd8d89f89895499fca2cff09f9e9e8c0 # v1.21.0
        with:
          fail_level: error
          filter_mode: nofilter
          reporter: github-pr-annotations
