name: reviewdog
on:
  push:
    branches: [main]
  pull_request:
permissions:
  contents: read
jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-yamllint@81e7f3cd56f50cf821aedc79b0ec169acf122532 # v1.20.2
        with:
          fail_level: error
          filter_mode: nofilter
          reporter: github-pr-annotations
