name: Ruff
on:
  push:
    branches: [main]
  pull_request:
permissions:
  contents: read
jobs:
  ruff:
    name: Ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@9828f49eb4cadf267b40eaa330295c412c68c1f9 # v3.2.2
      - run: ruff check --fix
      - run: ruff format --check
